version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass
# Пароль для дешифровки зашифрованных настроек в application.yml
      - PROPERTIES_PASSWORD=type_correct_pass
    networks:
      - nw
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    networks:
      - nw
networks:
  nw:
