server:
  port: 8080
spring:
  datasource:
    initialization-mode: never
    url: jdbc:postgresql://localhost:5432/mydb
    username: dbuser
    password: pass
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
geocoding:
  here:
#    Зашифрованный ключ для доступа к сервису
    apikey: ENC(Cg6tHOarEzxBziaitX1uuabtuIZjTYKErR+nSxUxkj2Exbc4x4c/3YKL8C/G/oee7NknHCnlOm0dnOlp3HVLmQ==)
properties:
#  Значение ключа для декодирования зашифрованных настроек. Настоящее значение передается через переменную окружения среды
  password: passstub
jasypt:
  encryptor:
    bean: appPropertiesEncryptor

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,logfile
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true